### ISSUE TITLE
Síntesis Gestión de proyectos de software

### ISSUE THREAD

**Issue by DavidFeria01** [SistemasTecTlaxiaco/sintesis-DavidFeria01#2]
[Sintesis gestion de proyectos de software.pdf](https://github.com/SistemasTecTlaxiaco/sintesis-DavidFeria01/files/7151374/Sintesis.gestion.de.proyectos.de.software.pdf)

**Comment by MaGuadalupeQuiroz** [comment]
El trabajo se presenta de forma ordenada, identifica las ideas principales y complementa la información con conceptos importantes de conocer.
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
